name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: BrowserStack Upload
        uses: Joey-Fuentes/android-build-action@v1.0.0
        with:
          project-path: BasicSample
          output-path: my-app.apk
          browserstack-upload: true
          browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
          browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
